apiVersion: apps/v1
kind: Deployment
metadata:
  name: webpage-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webpage
  template:
    metadata:
      labels:
        app: webpage
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: webpage-content
          mountPath: /usr/share/nginx/html
      volumes:
      - name: webpage-content
        configMap:
          name: webpage-config
